### ISSUE TITLE
Neo BIP 44 Address

### ISSUE THREAD

**Issue by JamesBingo** [coranos/ledger-wallet-raiblocks#4]
Why is the address NEO (0x80000378) and not RaiBlocks (0x800000a5)?

https://github.com/coranos/ledger-wallet-raiblocks/blob/7c8988f90b873aff87c3ae38f4d2eacbebbcdba7/scripts/app.jsx#L38

**Comment by coranos** [comment]
Ah, good catch :) I'll fix it.

**Comment by coranos** [comment]
fixed in commit 
https://github.com/coranos/ledger-wallet-raiblocks/commit/a602387c3a02754b25df4aa968b34ae88a4a7464

also updated blue-app-raiblocks
https://github.com/coranos/blue-app-raiblocks/commit/05b151494fbc259934d7f67dfff8779fba36b19f

this changes my ledger address from xrb_3wfre3yimmgi65cufus1q4snddypmhkgeout43sm76zj8pfd6tmh8bqoycei to xrb_14pjtq7kufnuzrroe5pjk4amdopozbo6g9bozpfjab8abkmaq941hkourxtg
